<?php

/**
 * @file
 * Defines Drupal hooks for Medium.
 */

/**
 * Implements hook_js_settings_alter().
 */
function medium_js_settings_alter(array &$settings, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  // XPreview library requires a tokenized URL.
  $libraries = \Drupal::service('library.dependency_resolver')->getLibrariesWithDependencies($assets->getLibraries());
  if (in_array('medium/drupal.xpreview', $libraries)) {
    $options = array();
    if (!\Drupal::currentUser()->isAnonymous()) {
      $options['query']['token'] = \Drupal::csrfToken()->get('xpreview');
    }
    $settings['xPreview']['url'] = \Drupal::url('drupal.xpreview', array(), $options);
  }
}

/**
 * Implements hook_library_info_alter().
 */
function medium_library_info_alter(array &$libraries, $module) {
  // Use dev version of MEDIUM library if dev mode is on.
  if ($module === 'medium' && \Drupal::config('medium.settings')->get('devmode')) {
    $libraries['MediumEditor'] = $libraries['MediumEditor.dev'];
  }
}
