# Module settings
medium.settings:
  type: mapping
  label: 'Medium settings'
  mapping:
    devmode:
      type: boolean
      label: 'Enable development mode'

# Medium Editor entity
medium.editor.*:
  type: config_entity
  label: 'Medium Editor'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Name'
    description:
      type: label
      label: 'Description'
    delay:
      type: label
      label: 'Delay'
    diffleft:
      type: label
      label: 'diffLeft'
    difftop:
      type: label
      label: 'diffTop'
    settings:
      type: sequence
      label: 'Settings'
      sequence:
        - type: medium.editor_settings.[%key]

# Editor settings
medium.editor_settings.toolbar:
  type: sequence
  label: 'Toolbar'
  sequence:
    - type: string
      label: 'Toolbar item'

medium.editor_settings.cname:
  type: string
  label: 'Class name'

medium.editor_settings.indent:
  type: boolean
  label: 'Enable indentation'

medium.editor_settings.acTags:
  type: boolean
  label: 'Autocomplete HTML tags'

# Medium Button entity
medium.button.*:
  type: config_entity
  label: 'Medium Button'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Name'
    tooltip:
      type: label
      label: 'Tooltip'
    text:
      type: string
      label: 'Button text'
    cname:
      type: string
      label: 'Class name'
    shortcut:
      type: string
      label: 'Shortcut'
    code:
      type: string
      label: 'Code'
    template:
      type: string
      label: 'Template'
    libraries:
      type: sequence
      label: 'Required libraries'
      sequence:
        - type: string
          label: 'Library name'

# Editor module plugin
editor.settings.medium:
  type: mapping
  label: 'Medium settings'
  mapping:
    default_editor:
      type: string
      label: 'Default editor'
    roles_editors:
      type: sequence
      label: 'Roles editors'
      sequence:
        - type: string
          label: 'Role editor'
